services:
  mysql:
    image: mysql:8
    container_name: agent-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Shanghai
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro

  redis:
    image: redis:8
    container_name: agent-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/data:/data
    command: >
      redis-server
      --requirepass "${REDIS_PASSWORD}"
      --bind 0.0.0.0
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --appendfilename "appendonly.aof"
      --dir /data
      --loglevel warning

  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: agent-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      TZ: Asia/Shanghai
    ports:
      - "${RABBITMQ_WEB_PORT}:15672"  # Web 管理界面
      - "${RABBITMQ_PORT}:5672"    # AMQP 协议端口
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime:ro

  minio:
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    container_name: agent-minio
    restart: always
    ports:
      - "${MINIO_API_PORT}:9000"  # S3 API 端口
      - "${MINIO_CONSOLE_PORT}:9001"  # 控制台端口
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      TZ: Asia/Shanghai
    volumes:
      - ./minio/data:/data
      - /etc/localtime:/etc/localtime:ro
    command: server /data --console-address ":9001"

# ==========================Milvus==========================
  milvus-etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:${MILVUS_ETCD} -listen-client-urls http://0.0.0.0:${MILVUS_ETCD} --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus-minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "${MILVUS_MINIO_1}:9001"
      - "${MILVUS_MINIO_2}:9000"
    volumes:
      - ./milvus-minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus-standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.12
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: milvus-etcd:${MILVUS_ETCD}
      MINIO_ADDRESS: milvus-minio:${MILVUS_MINIO_2}
    volumes:
      - ./milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "${MILVUS_STANDALONE_1}:19530"
      - "${MILVUS_STANDALONE_2}:9091"
    depends_on:
      - "milvus-etcd"
      - "milvus-minio"